### PR TITLE
Update Doc URLs

### PR DESCRIPTION
**Pull request by devinlyons**
Update URLs in the documentation.

### CODE REVIEW

**Comment by jtopjian** [comment]
@devinlyons Thanks! 

My apologies about this. The intention of having a doc only PR is to get you a committed PR and thus be able to have tests run on your other PR without my approval. This will allow you to develop and test faster. 

This PR looks good, but can you remove the references for "secrets"? This PR should just be kind of simple and affect existing things.

Let me know if this makes sense?

**Comment by devinlyons** [comment]
@jtopjian, I'm not sure what you mean by the reference to "secrets". Are you just wanting the URL updates in this PR and a later PR with the secrets documentation?

**Comment by jtopjian** [comment]
@devinlyons Correct. Just updating the URLs in the docs can be considered a general doc update PR. This will allow your Github account to then trigger the unit/acceptance tests without approval from here on out and you can continue work with Secrets.

**Comment by devinlyons** [comment]
@jtopjian, Done. I updated the rest of the docs while I was at it.

**Review by jtopjian — APPROVED** [review]
LGTM - thank you!

**Pull request merged**
