### PR TITLE
Add Support for Secrets

### PR DESCRIPTION
**Pull request by devinlyons**
Add support for passing secret configurations into checks, handlers, and mutators.

This partially completes the features requested in #43.

### CODE REVIEW

**Comment by jtopjian** [comment]
@devinlyons Thanks for submitting this. If you want to create a separate PR with just the doc changes, I can merge that which will allow further PRs to have their tests run without approval.

**Comment by devinlyons** [comment]
@jtopjian, I created #58 with just the docs. I will get this PR fixed up soon.

**Comment by devinlyons** [comment]
Okay, this PR should be ready to run again.

**Comment by devinlyons** [comment]
@jtopjian, just to clarify, once we are done with this PR, I should open another PR with just the new docs explaining the new secrets feature?

**Comment by jtopjian** [comment]
> just to clarify, once we are done with this PR, I should open another PR with just the new docs explaining the new secrets feature?

Nope. Everything can go in this original PR (minus the doc changes made in #58) but upon your next push, the unit/acceptance tests should run automatically for you.

**Comment by devinlyons** [comment]
@jtopjian, the docs are updated and the tests are passing.

**Review by jtopjian — CHANGES_REQUESTED** [review]
@devinlyons Thanks so much for your work on this and for your patience with getting that other PR committed.

This looks really good - nice work. The only request I have is to fix up the indenting on the test fixtures. It's not actually causing a problem, but better to get it formatted nicely now instead of setting precedence.

Let me know if you have any questions.

**Comment by devinlyons** [comment]
@jtopjian, I went through all the files and converted any space indentations to tabs.

**Review by jtopjian — APPROVED** [review]
LGTM - thank you!

**Comment by rshutt-va** [comment]
oh, so like I just now saw this!  So secrets work?!?!?! I just wrote a helm chart to deploy this thing to a 3az eks cluster with etcd/bitnami and my own bits housed form the sensu-k8s-quick-start (statefulset for backends, a job that fires until it succeeds on init, and a daemon set for the agent across 3 "node groups" of 1 node, each in their own AZ and with anti-affinity and EBS volume az dependencies to cause the perfect fanout of etcds at all times on 3 nodes, with the perfect fanout of backends (also statesfulsets) across the same three nodes and then the daemonset to guarantee 1 per node on the agents.  I was going to have to port the existing CI CD which was sensuctl wrappage. but maybe this is better now?  And yeah I needed secrets and vault integration so.

**Pull request merged**
