### PR TITLE
add pipelines attribute for the resource_check

### PR DESCRIPTION
**Pull request by shubhambjadhavar**

### CODE REVIEW

**Comment by jtopjian** [comment]
@shubhambjadhavar Thank you for working on this.

Do you know if Sensu 6 is required for this to work, or will it also work with 5? My concern is that this might break deployments for Sensu 5. But to be honest, I haven't used this provider in such a long time, I'm not sure if Sensu 5 is even widely used.

**Comment by shubhambjadhavar** [comment]
@jtopjian Sensu 5 don't have pipelines feature. This feature was introduced in [Sensu 6.5.0](https://docs.sensu.io/sensu-go/latest/release-notes/#650-release-notes).

**Comment by shubhambjadhavar** [comment]
@jtopjian I have updated the workflow to run the test cases for both the version you can check it once. It is not affecting the configuration with older sensu version.

**Review by jtopjian — APPROVED** [review]
LGTM - thank you!

**Comment by jtopjian** [comment]
@shubhambjadhavar My apologies for the delay with this. Thank you very much for your work and for contributing it.

**Comment by shubhambjadhavar** [comment]
Thanks @jtopjian

**Pull request merged**
