### PR TITLE
Support apikey auth

### PR DESCRIPTION
**Pull request by fgouteroux**
Hi @jtopjian,

It's been a while, ;-)

Adding support of api key authentication (more secure than username/password), based on https://github.com/sensu/sensu-go/pull/4256.

### CODE REVIEW

**Comment by fgouteroux** [comment]
Tested on sensu backend 5.21 and 6.2.5

**Comment by jtopjian** [comment]
@fgouteroux Cool - thanks for working on this. 

Overall this looks good to me. but now that username, password, and an API key are all _optional_, I think we should add some kind of additional logic to make sure that the user has supplied a valid combination of authentication. This should probably go in `LoadAndValidate` method. Something like:

```go
if c.username == "" && c.password == "" && c.apiKey == "" {
    return nil, fmt.Errorf("Must provide a username and password or an API key")
}

if c.username != "" && c.password == "" {
  return nil, fmt.Errorf("Must provide a password when using a username")
}

etc
```

Thoughts?

**Comment by fgouteroux** [comment]
> @fgouteroux Cool - thanks for working on this.
> 
> Overall this looks good to me. but now that username, password, and an API key are all _optional_, I think we should add some kind of additional logic to make sure that the user has supplied a valid combination of authentication. This should probably go in `LoadAndValidate` method. Something like:
> 
> ```go
> if c.username == "" && c.password == "" && c.apiKey == "" {
>     return nil, fmt.Errorf("Must provide a username and password or an API key")
> }
> 
> if c.username != "" && c.password == "" {
>   return nil, fmt.Errorf("Must provide a password when using a username")
> }
> 
> etc
> ```
> 
> Thoughts?

Yes, you are right, so I also added the schema conflicts keys, which provide this output when api_key and username/password are provided together. 

```go
Error: "api_key": conflicts with username

Error: "username": conflicts with api_key

Error: "password": conflicts with api_key
```

**Comment by jtopjian** [comment]
Nice work 🙂 

Let me know if you're ready for this to be merged.

**Comment by fgouteroux** [comment]
Yes, this is ready to be merged.

**Review by jtopjian — APPROVED** [review]
LGTM - thank you!

**Pull request merged**
