### PR TITLE
Labels and annotations checks support

### PR DESCRIPTION
**Pull request by fgouteroux**
Hi,

We want to add Labels and Annotations from Check Resource.
Based on work from https://github.com/Yelp/terraform-provider-sensu/pull/1.

```hcl
resource "sensu_check" "check_1" {
  name     = "my_check"
  command  = "/usr/local/bin/foo"
  interval = 600

  subscriptions = [
    "foo",
    "bar",
  ]
  annotations = {
    test = "annotation1"
  }
  labels = {
    test = "label1"
  }
}
```

### CODE REVIEW

**Comment by jtopjian** [comment]
@fgouteroux Thank you for working on this, too. Is it possible to add new tests or update the existing tests here:

* https://github.com/jtopjian/terraform-provider-sensu/blob/master/sensu/data_check_test.go
* https://github.com/jtopjian/terraform-provider-sensu/blob/master/sensu/resource_check_test.go

**Comment by fgouteroux** [comment]
> @fgouteroux Thank you for working on this, too. Is it possible to add new tests or update the existing tests here:
> 
>     * https://github.com/jtopjian/terraform-provider-sensu/blob/master/sensu/data_check_test.go
> 
>     * https://github.com/jtopjian/terraform-provider-sensu/blob/master/sensu/resource_check_test.go

I've no skills in tests U, I am bad and honestly I am not really passionate about it, but I will try.

**Comment by jtopjian** [comment]
> I've no skills in tests U, I am bad and honestly I am not really passionate about it, but I will try.

What you've provided is good - it's enough to make sure nothing breaks when using the feature in a simple way. I can amend the tests to be more comprehensive. Thank you!

**Review by jtopjian — APPROVED** [review]
LGTM - thank you!

**Pull request merged**
